"""empty message

Revision ID: 069c85e4024d
Revises: 822832828a38
Create Date: 2022-11-02 21:56:51.551252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069c85e4024d'
down_revision = '822832828a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('calories', sa.String(length=100), nullable=True),
    sa.Column('fat', sa.String(length=100), nullable=True),
    sa.Column('sugar', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('calories', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fat', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sugar', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe_table')
    # ### end Alembic commands ###
