"""empty message

Revision ID: 822832828a38
Revises: 87835d5f0eb5
Create Date: 2022-11-02 21:50:19.067610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822832828a38'
down_revision = '87835d5f0eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('calories', sa.String(length=100), nullable=True),
    sa.Column('fat', sa.String(length=100), nullable=True),
    sa.Column('sugar', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('ingredients_table')
    # ### end Alembic commands ###
